/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LabRouteImport } from './routes/lab'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgeSessionIdRouteImport } from './routes/forge.$sessionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeSessionIdRoute = ForgeSessionIdRouteImport.update({
  id: '/forge/$sessionId',
  path: '/forge/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/favorites': typeof FavoritesRoute
  '/lab': typeof LabRoute
  '/settings': typeof SettingsRoute
  '/forge/$sessionId': typeof ForgeSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/favorites': typeof FavoritesRoute
  '/lab': typeof LabRoute
  '/settings': typeof SettingsRoute
  '/forge/$sessionId': typeof ForgeSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/favorites': typeof FavoritesRoute
  '/lab': typeof LabRoute
  '/settings': typeof SettingsRoute
  '/forge/$sessionId': typeof ForgeSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/favorites'
    | '/lab'
    | '/settings'
    | '/forge/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/favorites' | '/lab' | '/settings' | '/forge/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/favorites'
    | '/lab'
    | '/settings'
    | '/forge/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  FavoritesRoute: typeof FavoritesRoute
  LabRoute: typeof LabRoute
  SettingsRoute: typeof SettingsRoute
  ForgeSessionIdRoute: typeof ForgeSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge/$sessionId': {
      id: '/forge/$sessionId'
      path: '/forge/$sessionId'
      fullPath: '/forge/$sessionId'
      preLoaderRoute: typeof ForgeSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  FavoritesRoute: FavoritesRoute,
  LabRoute: LabRoute,
  SettingsRoute: SettingsRoute,
  ForgeSessionIdRoute: ForgeSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
