import { useEffect, useState } from 'react'

import { DEFAULT_MODEL } from '#/features/key/key-repo'
import {
  clearApiKeyAndCache,
  ensureHydrated,
  getSettings,
  saveApiKey,
  saveModel,
} from '#/lib/settings'

const MODELS = [
  {
    id: 'claude-sonnet-4-6',
    label: 'Claude Sonnet 4.6 — fast, balanced (default)',
  },
  { id: 'claude-opus-4-8', label: 'Claude Opus 4.8 — highest quality' },
  { id: 'claude-haiku-4-5', label: 'Claude Haiku 4.5 — cheapest' },
]

/** BYO-key entry. The key lives only in this browser and is sent only to Anthropic. */
export function KeyEntry() {
  const [keyInput, setKeyInput] = useState('')
  const [model, setModel] = useState(DEFAULT_MODEL)
  const [hasKey, setHasKey] = useState(false)

  useEffect(() => {
    let active = true
    void ensureHydrated().then(() => {
      if (!active) return
      const settings = getSettings()
      setHasKey(Boolean(settings.apiKey))
      setModel(settings.model)
    })
    return () => {
      active = false
    }
  }, [])

  async function handleSaveKey() {
    const value = keyInput.trim()
    if (!value) return
    await saveApiKey(value)
    setKeyInput('')
    setHasKey(true)
  }

  async function handleClear() {
    await clearApiKeyAndCache()
    setHasKey(false)
  }

  async function handleModel(next: string) {
    setModel(next)
    await saveModel(next)
  }

  return (
    <div
      className="flex flex-col gap-5 rounded-2xl border p-6"
      style={{
        borderColor: 'var(--app-border)',
        background: 'var(--app-surface)',
      }}
    >
      <div className="flex flex-col gap-1">
        <h2
          className="text-base font-semibold"
          style={{ color: 'var(--app-text)' }}
        >
          Your Anthropic key
        </h2>
        <p className="text-sm" style={{ color: 'var(--app-muted)' }}>
          {hasKey
            ? 'A key is saved in this browser.'
            : 'Optional. With a key, palettes are generated by Claude using your own Anthropic account instead of the built-in generator.'}
        </p>
      </div>

      <div className="flex gap-2">
        <input
          type="password"
          value={keyInput}
          onChange={(e) => setKeyInput(e.target.value)}
          placeholder={hasKey ? 'Replace key (sk-ant-…)' : 'sk-ant-…'}
          spellCheck={false}
          autoComplete="off"
          className="flex-1 rounded-md border px-3 py-2 text-sm outline-none"
          style={{
            borderColor: 'var(--app-border)',
            background: 'var(--app-bg)',
            color: 'var(--app-text)',
          }}
        />
        <button
          type="button"
          onClick={() => void handleSaveKey()}
          disabled={keyInput.trim().length === 0}
          className="rounded-md px-4 py-2 text-sm font-medium disabled:opacity-40"
          style={{ background: 'var(--app-text)', color: 'var(--app-bg)' }}
        >
          Save
        </button>
        {hasKey && (
          <button
            type="button"
            onClick={() => void handleClear()}
            className="rounded-md border px-4 py-2 text-sm"
            style={{
              borderColor: 'var(--app-border)',
              color: 'var(--app-text)',
            }}
          >
            Clear
          </button>
        )}
      </div>

      <label
        className="flex flex-col gap-1 text-sm"
        style={{ color: 'var(--app-muted)' }}
      >
        Model
        <select
          value={model}
          onChange={(e) => void handleModel(e.target.value)}
          className="rounded-md border px-3 py-2 text-sm outline-none"
          style={{
            borderColor: 'var(--app-border)',
            background: 'var(--app-bg)',
            color: 'var(--app-text)',
          }}
        >
          {MODELS.map((m) => (
            <option key={m.id} value={m.id}>
              {m.label}
            </option>
          ))}
        </select>
      </label>

      <p
        className="text-xs leading-relaxed"
        style={{ color: 'var(--app-muted)' }}
      >
        Stored only in this browser (IndexedDB) and sent only to Anthropic — it
        never touches a server, which is what makes this free to host. Get a key
        from the{' '}
        <a
          href="https://console.anthropic.com/settings/keys"
          target="_blank"
          rel="noreferrer"
          className="underline"
          style={{ color: 'var(--app-text)' }}
        >
          Anthropic Console
        </a>
        .
      </p>
    </div>
  )
}
